### ISSUE TITLE
[backend] create an api endpoint for deleting the user account

### ISSUE THREAD

**Issue by fernanri** [Tech4covid19/trackovid19-backend#109]
The SQL commands for deleting the user account after obtaining the <user_id> and the <users_data_id> (from the JWT token) are:

delete from user_symptoms where history_id in (select h.id from history h where exists (select 1 from users u where u.id = <user_id> and u.id = h.user_id));
delete from history where user_id = <user_id>;
delete from users where id = <user_id>;
delete from users_data where id = <users_data_id>;

When creating this endpoint one should also change the user model in order to stop sending the hashed db tokens to the client (i.e. remove personal_hash and health_hash from the model).

**Comment by carlospombeiro** [comment]
Also delete user subscriptions
delete from public.push_subscriptions
where user_id = <user_id>

**Comment by pfortuna** [comment]
See this issue. It seems related:
https://github.com/Tech4covid19/trackovid19-web/issues/251

**Comment by skyhorse** [comment]
Additional requirements:
1) Dialog window to confirm data erasure request, namely stating it is not undoable and user will receive confirmation email once done
2) Erasure of the user-related events and data from backups and other possible storage locations
3) Audit trail needs to be implemented to record:
3.1) the original erasure request, including date/time, user authentication method and ids requested to be deleted
3.2) the erasure request confirmation, including date/time.

I propose 3) to be implemented via e-mail sending to a specific mailbox with the mentioned details.

**Comment by pfortuna** [comment]
- Send a SNS notification to Cloudwatch with the audit trail info

**Comment by pfortuna** [comment]
- After confirmed deletion, the user is forced logout, any cookies are deleted, the JWT token is invalidated

**Comment by carlospombeiro** [comment]
Audit trail data sample
`{"user_id":"6","user_data_id":"73b88669-b60a-4c40-abc0-06871195e3f9","request_date":"2020-03-27T20:07:29.769Z","authenticationProvider":"facebook"}`

**Comment by pfortuna** [comment]
You also need to return an indication to the client side if everything went ok.

{
"success": true
}

Or false, if otherwise.
