### ISSUE TITLE
[backend] Return Last Status update postal code

### ISSUE THREAD

**Issue by pfortuna** [Tech4covid19/trackovid19-backend#137]
Add a new property to /api/v1/user object being returned.

"lastupdate_postalcode": "XXXX-XXX"

This information *MUST* be fetched from the most recent update done from this user. This is stored in table "history", columns postalcode1 and postalcode2.

If the user has no update submitted, this property must not be returned at all.

**Comment by fernanri** [comment]
Would benefit from the same change devised in #120

**Comment by pfortuna** [comment]
Yes, #120 will close this one as well.
Since they are both assign to you, I will leave this to you.
