### ISSUE TITLE
Create local development environment

### ISSUE THREAD

**Issue by douglaspenna** [Tech4covid19/trackovid19-backend#25]
**Description**
Today it is not straightforward to test the code locally, before submitting a PR. It would be interesting if a developer could run a `docker-compose` command, and spin in their local machine everything necessary to run the local tests.

**Acceptance criteria**

- [ ] Have a docker compose file that spins off a container with PostgreSQL database, that can be run locally;
- [ ] Have in the docker compose file a container that encapsulates the logic of the node application.

**Comment by lcfb91** [comment]
moved to https://github.com/Tech4covid19/trackovid19-web/issues/30
