### ISSUE TITLE
[Readme.md] Production deploy command same as development

### ISSUE THREAD

**Issue by ludwig801** [Tech4covid19/trackovid19-backend#49]
![image](https://user-images.githubusercontent.com/5622673/76860333-c0d4cd00-6852-11ea-96d3-689be06a7e73.png)

**Comment by rumaf** [comment]
Production deploy command should be:

sls deploy --stage prd --db_pass 'PASSWORD'

**Comment by rumaf** [comment]
PR #55 fixes this issue
