### ISSUE TITLE
[backend] send web push notifications with Google Cloud Messaging

### ISSUE THREAD

**Issue by carlospombeiro** [Tech4covid19/trackovid19-backend#89]
Uses https://github.com/web-push-libs/web-push.
_This module makes it easy to send messages and will also handle legacy support for browsers relying on GCM for message sending / delivery._

**Comment by carlospombeiro** [comment]
* To use in client (browser) see example in /public/tests

* frontend must include a button to register browser subscription

* frontend must have a service-worker

**Comment by pfortuna** [comment]
- If the user subscribes, set the appropriate column in the database to true
